# -*- coding: utf-8 -*-
"""L4_exercicio-01a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYw-6HDgdXfZDQ5lPYiZ-QBWqt-ctof7

Exercício 01. Faça um programa para computar e apresentar a sequência de cada uma das seguintes séries numéricas, depois de ler um número inteiro n>=0: 1- LUCAS (2,1,3,4,7,11,18,29,47,...) 2- PELL (o,1,2,5,12,29,70,169,408,...) 3- Triangular (0,1,3,6,10,15,21,28,36,...) 4- Square (0,1,4,9,16,25,36,49,64,...) 5- Pentagonal (0,1,5,12,22,35,51,70,92,...)
"""

#definição das funções das series

def lucas (n):
    serie = [2, 1]
    if n > 1:
        for i in range(2, n+1):
            serie.append(serie[i-1] + serie[i-2])
        num = serie[i]
    return(serie)

def pell (n):
    serie = [0, 1]
    if n > 1:
        for i in range(2, n+1):
            serie.append(2*serie[i-1] + serie[i-2])
        num = serie[i]
    return(serie)

def triangular (n):
    serie = [int((x*(x+1))/2) for x in range(n+1)]
    return(serie)

def square (n):
    serie = [x**2 for x in range(n+1)]
    return(serie)

def pentagonal (n):
    serie = [int((3*x**2 -x)/2) for x in range(n+1)]
    return(serie)

ns = int(input("Entre com valor ns >= 0 : "))
if (ns < 0):
    print("Entre inteiro positivo")
else:
    print(f"n = {ns}")
    print("lucas: ", lucas(ns))
    print("pell: ", pell(ns))
    print("triangular: ", triangular(ns))
    print("square: ",square(ns))
    print("pentagonal: ", pentagonal(ns))