# -*- coding: utf-8 -*-
"""L4_exercicio-02a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g9rqtndeZGSZaeXID6_HWta_iTm5lJWs

Exercício 02. Escrever um programa em Python que simule uma calculadora com as funções básicas (+,-,/,*). O programa deve pedir ao usuário para entrar com os operandos (números reais) e o tipo de operação, e a seguir escrever o resultado. Assim como uma calculadora, que ao final de uma operação pode ser utilizada novamente, você deve simular este comportamento perguntando ao usuário se ele quer realizar uma nova operação.
"""

#operações
operacoes = ("+", "-", "/", "*" )

n1 = float(input("Digite o primeiro número: "))
oper = input("Digite a operação: + - / * ")

while oper in operacoes:
    n2 = float(input("Digite o segundo número: "))

    if operacoes.index(oper) == 0:
        print(f'{n1} {oper} {n2} = {(n1 + n2)}')
        oper = input("Escolha a operação: + - * / ")
        n1 = n1 + n2

    elif operacoes.index(oper) == 1:
        print(f'{n1} {oper} {n2} = {(n1 - n2)}')
        oper = input("Escolha a operação: + - * / ")
        n1 = n1 - n2

    elif operacoes.index(oper) == 2:
        print(f'{n1} {oper} {n2} = {(n1 * n2)}')
        oper = input("Escolha a operação: + - * / ")
        n1 = n1 * n2

    elif n2 == 0:
        print("O denominador deve ser diferente de zero.")
        break

    elif operacoes.index(oper) == 3:
        print(f'{n1} {oper} {n2} = {(n1 / n2)}')
        oper = input("Escolha a operação (+ - * / )")
        n1 = n1 / n2
    else:
        print("Entre com uma opreçao válida.")
        break

print("Fim Operação")